---
version: '3.4'
services:
  db:
    image: postgres:9.5.4
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports: ["5432:5432"]
  app: &app-common
    build: "."
    command: bin/rails -- passenger start -p 3000do
    environment: &app-environment
      DATABASE_URL: postgresql://postgres:postgrespassword@db
      REDIS_URL: redis://redis:6379
    links:
    - db
    - redis
    volumes: [".:/app"]
    ports: ["3000:3000"]
  redis:
    image: redis:5.0.3
    ports: ["6379:6379"]
  app-sidekiq-workers:
    <<: *app-common
    command: bin/rails -- bin/rails -- bundle exec sidekiq
    ports: []
    environment:
      <<: *app-environment
      DB_POOL: 1
      SIDEKIQ_CONCURRENCY: 1